# Generated by Django 3.2.8 on 2022-07-07 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.domain')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500, null=True)),
                ('date', models.DateField(null=True)),
                ('rank', models.IntegerField(null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.domain')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.keyword')),
            ],
        ),
        migrations.AddConstraint(
            model_name='rank',
            constraint=models.UniqueConstraint(fields=('domain', 'keyword', 'date', 'rank'), name='rank_unique'),
        ),
        migrations.AddConstraint(
            model_name='keyword',
            constraint=models.UniqueConstraint(fields=('name', 'domain'), name='keyword_unique'),
        ),
        migrations.AddConstraint(
            model_name='domain',
            constraint=models.UniqueConstraint(fields=('name', 'user'), name='domain_unique'),
        ),
    ]
