# Generated by Django 4.0.1 on 2022-06-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='keyword',
            constraint=models.UniqueConstraint(fields=('name', 'domain'), name='keyword_unique'),
        ),
    ]
